version: '3.8'

services:
  app:
    build:
      target: development
    environment:
      - NODE_ENV=development
      - DB_PASSWORD=postgres
      - JWT_SECRET=dev_secret
      - DB_HOST=postgres
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/api_db
    volumes:
      - ./src:/app/src
      - ./dist:/app/dist
    ports:
      - "3000:3000"
    command: npm run dev

  migrations:
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=api_db
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/api_db
    volumes:
      - ./migrations:/app/migrations

  postgres:
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=api_db
    ports:
      - "5432:5432" 