name: CI

on:
  push:
    branches: [ main, feature/github-actions-setup ]
  pull_request:
    branches: [ main, feature/github-actions-setup ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DB_NAME }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Verify PostgreSQL Connection
        run: |
          sudo apt-get install -y postgresql-client
          PGPASSWORD=postgres psql -h localhost -U postgres -d api_db -c '\l'
          PGPASSWORD=postgres psql -h localhost -U postgres -d api_db -c '\dt'

      - name: Run Database Migrations
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/api_db
          NODE_ENV: test
        run: npm run migrate:up

      - name: Verify Tables After Migration
        run: |
          PGPASSWORD=postgres psql -h localhost -U postgres -d api_db -c '\dt'

      - name: Run tests
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/api_db
          NODE_ENV: test
          JWT_SECRET: myjwtsecret
        run: npm test
   